// Package placement_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package placement_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Placement defines model for Placement.
type Placement struct {
	Height *int    `json:"height,omitempty"`
	Seats  *[]Seat `json:"seats,omitempty"`
	Width  *int    `json:"width,omitempty"`
}

// Seat defines model for Seat.
type Seat struct {
	Floor    *int     `json:"floor,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Rotation *float32 `json:"rotation,omitempty"`
	Space    *int     `json:"space,omitempty"`
	True     *float32 `json:"true,omitempty"`
	Width    *int     `json:"width,omitempty"`
	X        *float32 `json:"x,omitempty"`
}

// PutPlacementBusinessIdJSONBody defines parameters for PutPlacementBusinessId.
type PutPlacementBusinessIdJSONBody Placement

// PutPlacementBusinessIdRequestBody defines body for PutPlacementBusinessId for application/json ContentType.
type PutPlacementBusinessIdJSONRequestBody PutPlacementBusinessIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /placement/{businessId})
	GetPlacementBusinessId(ctx echo.Context, businessId string) error

	// (PUT /placement/{businessId})
	PutPlacementBusinessId(ctx echo.Context, businessId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPlacementBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlacementBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPlacementBusinessId(ctx, businessId)
	return err
}

// PutPlacementBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PutPlacementBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutPlacementBusinessId(ctx, businessId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/placement/:businessId", wrapper.GetPlacementBusinessId)
	router.PUT(baseURL+"/placement/:businessId", wrapper.PutPlacementBusinessId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUTW/bMAz9KwK3oxG73Wk+BhuGADsUG3YaepBlOlYhSypFZQsC//dBsvPVeMUuA3qK",
	"JZKPj++JOYByg3cWLQeoDxBUj4PMnw9GKhzQcjp4ch6JNeZQj3rb53vee4QatGXcIsFYQEA5QWnGIX+8",
	"J+yghnfluVU59ym/o+RUNeNIIrlP51+65X6pwTnXNU+ocnEGuSHZGedomeNr/K0c8CISmLTdpgA5lqyd",
	"vQjaODTz1F4qXAZkirhY89cZC/i9UHA7ebrStnMpucWgSPuJIHy2rXfasugciSSPQcVCtoO2YpBWbrOx",
	"whvJnaMBCmDNJmGfXS9ghxQmvLtVlWg5j1Z6DTV8WFWreyjAS+6z2qU/FpaHJgZtMYRNO6bQFvmW4Rdk",
	"sZ7zhL9omizMOm/aKe3EaH2CzY1JDshIAeqfL8E3n4TrBPd4agFJKagzXziaDM0lIuFz1IQt1MmxYl6F",
	"hacwPqbk4J0N00u7r6r0o5zleV2k90arPEb5FKY3c8Z7bSHO+md7r+f6hkwad9iK5kY6EaJSGEIXjdlP",
	"xT4uCP/Dt5LxX7R/iG9V++eIgdeu3f8v2a/5jMt+X899QhAxK9wmpDH/IdLuKFUkAzX0zL4uS+OUNL0L",
	"XB+8Ix5L6XW5u4OXrn9NeWKCSVspScvGTFRS4cSlk9Ew1PCxqqrU+nH8EwAA///Pie7O3AUAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
