// Package business_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package business_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Business defines model for Business.
type Business struct {
	Id           *string   `json:"_id,omitempty"`
	Address      *string   `json:"address,omitempty"`
	BusinessName *string   `json:"businessName,omitempty"`
	Description  *string   `json:"description,omitempty"`
	DisplayImage *string   `json:"displayImage,omitempty"`
	Images       *[]string `json:"images,omitempty"`
	Location     *struct {
		Latitude  *string `json:"latitude,omitempty"`
		Longitude *string `json:"longitude,omitempty"`
	} `json:"location,omitempty"`
	Policy *struct {
		MinAge *int `json:"minAge,omitempty"`
	} `json:"policy,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	Type *string   `json:"type,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /business/{businessId})
	GetBusinessBusinessId(ctx echo.Context, businessId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBusinessBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetBusinessBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBusinessBusinessId(ctx, businessId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/business/:businessId", wrapper.GetBusinessBusinessId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RT3YrbPBB9FTPfdxki7/aquuuyUAKlL1CWotgTZxZZUkfjgAl59zKynWx2XWiv9DOj",
	"c+bozJyhiX2KAYNksGfIzRF7V7ZPQ6aAuewTx4QshOX0k1pdZEwIFrIwhQ4uG3Bty/ODD7H9jPbd9bia",
	"0GJumJJQDOtxysm7cde7bh2ANFLISbBfr2K+cMxu1LOPjVsY7zV6JyRDu07lY+j+FL2xxP0rNqL5KXpq",
	"xo8kPYUvd2ooCHbI6yjiun+UN53/okS9onCIJZnEa+zq/wZOyLn8Ejxs622t0DFhcInAwqdtvX2EDSQn",
	"x1KWWbw252W3ay8a6VB0ubMavqJUC1elRXBfPKn2Y7V7hkLF5WbXTulL9tMVvdCz61GQM9gf7zl2z1U8",
	"VHLE6o0q0ohWDRsIpS1h/xaR8ddAjC1Y4QE382ys/eeLJucUQ558faxrXZoYBEOR7FLyNPWaec1Tw93w",
	"/mc8gIX/zG0YzTyJ5lpwMele1uq3MQoTnrCt8tA0mPNh8H7U5wqQkU/LHw3swcJRJFljdBT8MWax5xRZ",
	"LsYlMqcHeM/5TfOqCUZbwzG5vZ9068PJ4IMbvICFz3VdK/XL5XcAAAD//6qcj3VqBAAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
