// Package business_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package business_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// AppendImageResponse defines model for AppendImageResponse.
type AppendImageResponse struct {
	Image *string `json:"image,omitempty"`
}

// Business defines model for Business.
type Business struct {
	Id           *string   `json:"_id,omitempty"`
	Address      *string   `json:"address,omitempty"`
	BusinessName *string   `json:"businessName,omitempty"`
	Description  *string   `json:"description,omitempty"`
	DisplayImage *string   `json:"displayImage,omitempty"`
	Images       *[]string `json:"images,omitempty"`
	Location     *Location `json:"location,omitempty"`
	Tags         *[]string `json:"tags,omitempty"`
	Type         *string   `json:"type,omitempty"`
}

// GetMenuResponse defines model for GetMenuResponse.
type GetMenuResponse struct {
	Menu *[]MenuItem `json:"menu,omitempty"`
}

// ImageUpload defines model for ImageUpload.
type ImageUpload string

// ListBusinessResponse defines model for ListBusinessResponse.
type ListBusinessResponse struct {
	Businesses *[]Business `json:"businesses,omitempty"`
	MaxPage    *int        `json:"maxPage,omitempty"`
}

// Location defines model for Location.
type Location struct {
	Latitude  *float32 `json:"latitude,omitempty"`
	Longitude *float32 `json:"longitude,omitempty"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Name        *string `json:"name,omitempty"`
	Price       *string `json:"price,omitempty"`
}

// UpdateBusinessRequest defines model for UpdateBusinessRequest.
type UpdateBusinessRequest struct {
	Id           *string   `json:"_id,omitempty"`
	Address      *string   `json:"address,omitempty"`
	BusinessName *string   `json:"businessName,omitempty"`
	Description  *string   `json:"description,omitempty"`
	Location     *Location `json:"location,omitempty"`
	Tags         *[]string `json:"tags,omitempty"`
	Type         *string   `json:"type,omitempty"`
}

// UpdateDisplayImageResponse defines model for UpdateDisplayImageResponse.
type UpdateDisplayImageResponse struct {
	DisplayImage *string `json:"displayImage,omitempty"`
}

// UpdateStatusRequest defines model for UpdateStatusRequest.
type UpdateStatusRequest struct {
	Status *int `json:"status,omitempty"`
}

// GetBusinessParams defines parameters for GetBusiness.
type GetBusinessParams struct {
	Status int `json:"status"`
	Page   int `json:"page"`
}

// PatchBusinessBusinessIdJSONBody defines parameters for PatchBusinessBusinessId.
type PatchBusinessBusinessIdJSONBody UpdateBusinessRequest

// PostBusinessBusinessIdMenuitemsJSONBody defines parameters for PostBusinessBusinessIdMenuitems.
type PostBusinessBusinessIdMenuitemsJSONBody MenuItem

// PatchBusinessBusinessIdStatusJSONBody defines parameters for PatchBusinessBusinessIdStatus.
type PatchBusinessBusinessIdStatusJSONBody UpdateStatusRequest

// PatchBusinessBusinessIdRequestBody defines body for PatchBusinessBusinessId for application/json ContentType.
type PatchBusinessBusinessIdJSONRequestBody PatchBusinessBusinessIdJSONBody

// PostBusinessBusinessIdMenuitemsRequestBody defines body for PostBusinessBusinessIdMenuitems for application/json ContentType.
type PostBusinessBusinessIdMenuitemsJSONRequestBody PostBusinessBusinessIdMenuitemsJSONBody

// PatchBusinessBusinessIdStatusRequestBody defines body for PatchBusinessBusinessIdStatus for application/json ContentType.
type PatchBusinessBusinessIdStatusJSONRequestBody PatchBusinessBusinessIdStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /business)
	GetBusiness(ctx echo.Context, params GetBusinessParams) error

	// (GET /business/{businessId})
	GetBusinessBusinessId(ctx echo.Context, businessId string) error

	// (PATCH /business/{businessId})
	PatchBusinessBusinessId(ctx echo.Context, businessId string) error

	// (PUT /business/{businessId}/displayImage)
	PutBusinessBusinessIdDisplayImage(ctx echo.Context, businessId string) error

	// (POST /business/{businessId}/images)
	PostBusinessBusinessIdImages(ctx echo.Context, businessId string) error

	// (DELETE /business/{businessId}/images/{pos})
	DeleteBusinessBusinessIdImagesPos(ctx echo.Context, businessId string, pos int) error

	// (GET /business/{businessId}/menu)
	GetBusinessBusinessIdMenu(ctx echo.Context, businessId string) error

	// (POST /business/{businessId}/menuitems)
	PostBusinessBusinessIdMenuitems(ctx echo.Context, businessId string) error

	// (DELETE /business/{businessId}/menuitems/{name})
	DeleteBusinessBusinessIdMenuitemsName(ctx echo.Context, businessId string, name string) error

	// (PATCH /business/{businessId}/status)
	PatchBusinessBusinessIdStatus(ctx echo.Context, businessId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBusiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetBusiness(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBusinessParams
	// ------------- Required query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, true, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBusiness(ctx, params)
	return err
}

// GetBusinessBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetBusinessBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBusinessBusinessId(ctx, businessId)
	return err
}

// PatchBusinessBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchBusinessBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchBusinessBusinessId(ctx, businessId)
	return err
}

// PutBusinessBusinessIdDisplayImage converts echo context to params.
func (w *ServerInterfaceWrapper) PutBusinessBusinessIdDisplayImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBusinessBusinessIdDisplayImage(ctx, businessId)
	return err
}

// PostBusinessBusinessIdImages converts echo context to params.
func (w *ServerInterfaceWrapper) PostBusinessBusinessIdImages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostBusinessBusinessIdImages(ctx, businessId)
	return err
}

// DeleteBusinessBusinessIdImagesPos converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBusinessBusinessIdImagesPos(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// ------------- Path parameter "pos" -------------
	var pos int

	err = runtime.BindStyledParameter("simple", false, "pos", ctx.Param("pos"), &pos)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pos: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteBusinessBusinessIdImagesPos(ctx, businessId, pos)
	return err
}

// GetBusinessBusinessIdMenu converts echo context to params.
func (w *ServerInterfaceWrapper) GetBusinessBusinessIdMenu(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBusinessBusinessIdMenu(ctx, businessId)
	return err
}

// PostBusinessBusinessIdMenuitems converts echo context to params.
func (w *ServerInterfaceWrapper) PostBusinessBusinessIdMenuitems(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostBusinessBusinessIdMenuitems(ctx, businessId)
	return err
}

// DeleteBusinessBusinessIdMenuitemsName converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBusinessBusinessIdMenuitemsName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameter("simple", false, "name", ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteBusinessBusinessIdMenuitemsName(ctx, businessId, name)
	return err
}

// PatchBusinessBusinessIdStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PatchBusinessBusinessIdStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchBusinessBusinessIdStatus(ctx, businessId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/business", wrapper.GetBusiness)
	router.GET(baseURL+"/business/:businessId", wrapper.GetBusinessBusinessId)
	router.PATCH(baseURL+"/business/:businessId", wrapper.PatchBusinessBusinessId)
	router.PUT(baseURL+"/business/:businessId/displayImage", wrapper.PutBusinessBusinessIdDisplayImage)
	router.POST(baseURL+"/business/:businessId/images", wrapper.PostBusinessBusinessIdImages)
	router.DELETE(baseURL+"/business/:businessId/images/:pos", wrapper.DeleteBusinessBusinessIdImagesPos)
	router.GET(baseURL+"/business/:businessId/menu", wrapper.GetBusinessBusinessIdMenu)
	router.POST(baseURL+"/business/:businessId/menuitems", wrapper.PostBusinessBusinessIdMenuitems)
	router.DELETE(baseURL+"/business/:businessId/menuitems/:name", wrapper.DeleteBusinessBusinessIdMenuitemsName)
	router.PATCH(baseURL+"/business/:businessId/status", wrapper.PatchBusinessBusinessIdStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYTW/jNhD9KwTboxA5216qW40AhYFkEexiT8WioKWxzIVEMuTIrWHovxck9WWLUpRu",
	"ghrZk2WRnBm+92bI0YmmslRSgEBDkxM16R5K5h5/VwpEtilZDp/AKCkM2NdKSwUaObhJ3A7bBzwqoAk1",
	"qLnIaV1H7Ru5/QYp0jqi68pwAcaMrfzFs4CNiLIs082C0di2sfaRlRCckIFJNVfIpQiPc6MKdtxM7CDy",
	"e/O7RCjDUTQvmNbsaP8XMmWtx5817GhCf4p7iOMG3/i+nWdtsPyFXvz/RaD/AfgAoppmsARRnXmfC9ua",
	"2iCU46BCvh20X1QhmaN3J3XJkCZ0zQXTRxqNN3rPDbYymQ65pf6CnLnAO+0F0CzZP4/nGuACIQcd3tX9",
	"gOLzuAqGHKtsaElU5dYassoQ+dRoyE0H9cjNc8Lmk4oWU7miNE+XKuqLyhhCz9JTBQavJKevLv08WHeD",
	"UjMt62cK0rT5z8iwmmbCuOFl8ravuNhJN5tjYce63InoAbRx8NLbm9XNyoYgFQimOE3oLzermw80oorh",
	"3rmLt4OKnwOOxGurEym4QSJ3pM9qsj0SHzRhIiOK5UCaVHH+tONuk3kDg/AU06wEBG1o8ueJcuviqQJX",
	"a7z2WzAiquGp4hoymqCuIGpOvjBKYVM2rpcZ+mpne/odJh9WK/uTSoEgHDxMqYJ7bcbfjBdyb3BW0qHS",
	"6fg8h/wToOZwgKwDft0Db6o0BWN2VVHYmm5XdyTGp/Zpk9WzjLYGiVWSrflcCsvp5m6Ov3VnfczkuY/N",
	"nQ0b90AG3DuGrPR6grZDi8/S1OXZW7LUn0NjZoKw6Y6uS25coqX7MQW+KLyEhUdraAkP/x3kBQwGeXA1",
	"bS2z46tRED6/HKDn4ddhHSwgrXIusuXpFF/WflXh88QOF00xWwXya3gcXTPH7iITK5EvJ3d45awbTt8o",
	"lWeO9kByN/OI21MrkHlN9P2HkiYgB9+gEUYE/N3YRTlIe798pAhpApLYtJN/KDHcvpoYQs1yQAU+VZmb",
	"vIz++KSkqT2gBSCMob1z7wkTjQa46DWQ8wMIwtEQJQ13Cy714JdPKeJR/t+iiIL+lDTfe/X6NRCQA9AD",
	"nZGdliUZHtjTXLVN9OSVyG6yvW/ZycR3G4uuQ7YTvIbMfKM6evmFIpA29yPkZu5F8yx1Xd6Cmtq5s3XV",
	"IlR6JpYU1IfO17u8RPUfgkJ1NZBaDx2Wy6pfx1V8shgtqoCkXTSoew7gpTWvI+2jX3V9da/Zzvc0M69Z",
	"9/pPC/O9yHCvbWu/41BkS1uRz23b/m4bkvOPOEvTyq86u0/WETWgDy1ClS5oQveIKonjQqas2EuDyUlJ",
	"jXXMFI8Pt3RUcO084s3QiB6Y5mxbtJdR3RTOHasKpAn9bbVaWddf638DAAD//9BSMr5PGAAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
