// Package request_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package request_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Id           *string `json:"_id,omitempty"`
	Address      *string `json:"address,omitempty"`
	BusinessName *string `json:"businessName,omitempty"`
	Description  *string `json:"description,omitempty"`
	Location     *struct {
		Latitude  *float32 `json:"latitude,omitempty"`
		Longitude *float32 `json:"longitude,omitempty"`
	} `json:"location,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	Type *string   `json:"type,omitempty"`
}

// ListRequestResponse defines model for ListRequestResponse.
type ListRequestResponse struct {
	MaxPage *int             `json:"maxPage,omitempty"`
	Request *[]ChangeRequest `json:"request,omitempty"`
}

// GetRequestParams defines parameters for GetRequest.
type GetRequestParams struct {
	Page int `json:"page"`
}

// PostRequestBusinessIdJSONBody defines parameters for PostRequestBusinessId.
type PostRequestBusinessIdJSONBody ChangeRequest

// PostRequestBusinessIdRequestBody defines body for PostRequestBusinessId for application/json ContentType.
type PostRequestBusinessIdJSONRequestBody PostRequestBusinessIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /request)
	GetRequest(ctx echo.Context, params GetRequestParams) error

	// (GET /request/{businessId})
	GetRequestBusinessId(ctx echo.Context, businessId string) error

	// (POST /request/{businessId})
	PostRequestBusinessId(ctx echo.Context, businessId string) error

	// (POST /request/{businessId}/approve)
	PostRequestBusinessIdApprove(ctx echo.Context, businessId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetRequest converts echo context to params.
func (w *ServerInterfaceWrapper) GetRequest(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRequestParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRequest(ctx, params)
	return err
}

// GetRequestBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetRequestBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRequestBusinessId(ctx, businessId)
	return err
}

// PostRequestBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PostRequestBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostRequestBusinessId(ctx, businessId)
	return err
}

// PostRequestBusinessIdApprove converts echo context to params.
func (w *ServerInterfaceWrapper) PostRequestBusinessIdApprove(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostRequestBusinessIdApprove(ctx, businessId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/request", wrapper.GetRequest)
	router.GET(baseURL+"/request/:businessId", wrapper.GetRequestBusinessId)
	router.POST(baseURL+"/request/:businessId", wrapper.PostRequestBusinessId)
	router.POST(baseURL+"/request/:businessId/approve", wrapper.PostRequestBusinessIdApprove)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yV32vbMBDH/xVx26OJ3W4v89vWQSmUUfI6ylDss6NiS+rpnC2E/O9Dkp3EsdOOQaFP",
	"dvTj7nvfz128g8K01mjU7CDfgSvW2MrwerOWusYlPnfo2C9YMhaJFYbtX6r0D95ahBwck9I17BOQZUno",
	"3OzeqnNKo3M/ZIuzB0p0BSnLyujZ/cYUctgcy2kkK+7K07C6a1dI8ZquL+3uk2HFrJ6wYH+eZR2CKsZ2",
	"vpJ+QRLJ7fH35OBc8HvluHd1ic4a7XBaTiv/PMj6NKTSjHUsh45MDgo/ElaQw4f0yDPtYaZjkhP1U5F+",
	"SenKhPSKG783XE9gg+QCA7haZIvMBzQWtbQKcvi0yBbXkICVvA7C0hO1NYbHiHLwQwydIaQuhWIniqBZ",
	"9JeFV0NtZB/SUXi/KyGHW+SjOCtJtshIDvKfO1A+w3OHtIUEdGg7sN7Y6KIiLCFn6jDpW3/O8f2jPx1R",
	"hZqus8w/CqMZdShJWtuo2Jvpk4sNegz4Epy5dggAxi4tkUnhBkXj7TLV2LEzt1xXFOhc1TWN5+ujDRjS",
	"3XDxrtxfZHKLLKRwFgtVqeIs/AsAvh1iT1GMM9x990XwGsVwB5JIy3fOEdbqNOKryA5z95bEzsZpyurm",
	"Yu8K6jGWE0YJWONmUNwQSkYhhcbf55wrQ0IeOmHC5cG49wkmSjLl9i2ZjDXtJw1xddHr/5ymVFpLZhP/",
	"zWdZfo0HTpi9NlqzCPsw727EPk8rHjL/4xB4bx3SZiioowZyWDPbPE39x79ZG8f5zhpi77dKN1dwPn73",
	"/pyIYfznSpKSqyaK9Bejykp2DUMOX7Is86kf938DAAD//2sGheoMCQAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
