// Package reservation_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package reservation_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// CreateReservationRequest defines model for CreateReservationRequest.
type CreateReservationRequest struct {
	End   *string `json:"end,omitempty"`
	Name  *string `json:"name,omitempty"`
	Start *string `json:"start,omitempty"`
}

// ListReservationRequest defines model for ListReservationRequest.
type ListReservationRequest struct {
	End   *string `json:"end,omitempty"`
	Start *string `json:"start,omitempty"`
}

// ListReservationResponse defines model for ListReservationResponse.
type ListReservationResponse struct {
	Reservations *Reservation `json:"reservations,omitempty"`
}

// Placement defines model for Placement.
type Placement struct {
	Height *int    `json:"height,omitempty"`
	Seats  *[]Seat `json:"seats,omitempty"`
	Width  *int    `json:"width,omitempty"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	End       *string    `json:"end,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Placement *Placement `json:"placement,omitempty"`
	Start     *string    `json:"start,omitempty"`
}

// Seat defines model for Seat.
type Seat struct {
	Floor    *int     `json:"floor,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Rotation *float32 `json:"rotation,omitempty"`
	Space    *int     `json:"space,omitempty"`
	Status   *string  `json:"status,omitempty"`
	True     *float32 `json:"true,omitempty"`
	User     *string  `json:"user,omitempty"`
	Width    *int     `json:"width,omitempty"`
	X        *float32 `json:"x,omitempty"`
}

// GetReservationBusinessIdJSONBody defines parameters for GetReservationBusinessId.
type GetReservationBusinessIdJSONBody ListReservationRequest

// PostReservationBusinessIdJSONBody defines parameters for PostReservationBusinessId.
type PostReservationBusinessIdJSONBody CreateReservationRequest

// GetReservationBusinessIdRequestBody defines body for GetReservationBusinessId for application/json ContentType.
type GetReservationBusinessIdJSONRequestBody GetReservationBusinessIdJSONBody

// PostReservationBusinessIdRequestBody defines body for PostReservationBusinessId for application/json ContentType.
type PostReservationBusinessIdJSONRequestBody PostReservationBusinessIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /reservation/{businessId})
	GetReservationBusinessId(ctx echo.Context, businessId string) error

	// (POST /reservation/{businessId})
	PostReservationBusinessId(ctx echo.Context, businessId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReservationBusinessId(ctx, businessId)
	return err
}

// PostReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PostReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostReservationBusinessId(ctx, businessId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/reservation/:businessId", wrapper.GetReservationBusinessId)
	router.POST(baseURL+"/reservation/:businessId", wrapper.PostReservationBusinessId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RVQW/bPAz9KwK/7xjUbneaj92GoUAPRXccemBsOlYhSypFpwuC/PdBstM4jdJtKHba",
	"KbFEPT6+R0pbqF3vnSUrAaothLqjHtPfT0wodE+BeI2inb2np4GCxD3PzhOLphRJtok/svEEFQRhbVew",
	"W4DFnrIbQZAls7Nb7Ffc8pFqibG3Osh7SLwrV/DOBjpNxoeg9P0/UwsV/Fcc1CwmKYsZYD7rncGaerKZ",
	"ojrSq27OXluhFXEqjHD0TAv1v2TxjTAlm3CQGTfx+1k30uUS5JjOS3l/F/h53W9xPwj0h36mok+ItsY5",
	"zmv6lt5n62AnL5JMm3bol5NLHms6Y6CgDCELKTxQFm4IxNkTZ31cwI8M0qlacUnb1sXghkLN2o9FwRfb",
	"eKetqNaxipIaqkVh02urerS4St4ob1Baxz0sQLSYiD3vlwWsicOIeHlRRmLOk0WvoYIPF+XFFSzAo3RJ",
	"kWI2YcV2OQRtKYSbZhc3VySnLOPsKlT7UHU0oikXp4+bBir4SvM5v36BTxQYexLiANX310luPivXKulI",
	"7c9AVA2qxBz2TQLLOSLT06CZGqiirYvpjs218MMYTEGuXbOJEbWzMk0Iem90PSryGMZ2O0C9NT9nrtBk",
	"+TG5tDBeesmGq7L8eyymyzXROJb5noQ1ralRJrrq2iM3VRjqmkJoB2M243HvQqYlxhdMobL0PEc4aYc7",
	"F/6lfjj7sv9WR1yeCj2DUiN4E7F26ZXi9V67gQ1U0In4qiiMq9F0Lki19Y5lV6DXxfoSXvfCbYxTI0y8",
	"RJA1Ls1IJh4c2bQ4GIEKPpZlGVM/7H4GAAD//xIxprvaCAAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
