// Package reservation_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package reservation_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// CreateReservationRequest defines model for CreateReservationRequest.
type CreateReservationRequest struct {
	End   *string `json:"end,omitempty"`
	Name  *string `json:"name,omitempty"`
	Start *string `json:"start,omitempty"`
}

// GetReservationResponse defines model for GetReservationResponse.
type GetReservationResponse struct {
	Reservation *Reservation `json:"reservation,omitempty"`
}

// ListReservationRequest defines model for ListReservationRequest.
type ListReservationRequest struct {
	End   *string `json:"end,omitempty"`
	Start *string `json:"start,omitempty"`
}

// ListReservationResponse defines model for ListReservationResponse.
type ListReservationResponse struct {
	Reservations *[]Reservation `json:"reservations,omitempty"`
}

// Placement defines model for Placement.
type Placement struct {
	Height *int    `json:"height,omitempty"`
	Seats  *[]Seat `json:"seats,omitempty"`
	Width  *int    `json:"width,omitempty"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	End       *string    `json:"end,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Placement *Placement `json:"placement,omitempty"`
	Start     *string    `json:"start,omitempty"`
}

// Seat defines model for Seat.
type Seat struct {
	Floor    *int     `json:"floor,omitempty"`
	Height   *float32 `json:"height,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Rotation *float32 `json:"rotation,omitempty"`
	Space    *int     `json:"space,omitempty"`
	Status   *string  `json:"status,omitempty"`
	Type     *string  `json:"type,omitempty"`
	User     *string  `json:"user,omitempty"`
	Width    *float32 `json:"width,omitempty"`
	X        *float32 `json:"x,omitempty"`
	Y        *float32 `json:"y,omitempty"`
}

// UpdateStatusRequest defines model for UpdateStatusRequest.
type UpdateStatusRequest struct {
	Status *int `json:"status,omitempty"`
}

// GetReservationBusinessIdJSONBody defines parameters for GetReservationBusinessId.
type GetReservationBusinessIdJSONBody ListReservationRequest

// PostReservationBusinessIdJSONBody defines parameters for PostReservationBusinessId.
type PostReservationBusinessIdJSONBody CreateReservationRequest

// PatchReservationReservationIdStatusJSONBody defines parameters for PatchReservationReservationIdStatus.
type PatchReservationReservationIdStatusJSONBody UpdateStatusRequest

// GetReservationBusinessIdRequestBody defines body for GetReservationBusinessId for application/json ContentType.
type GetReservationBusinessIdJSONRequestBody GetReservationBusinessIdJSONBody

// PostReservationBusinessIdRequestBody defines body for PostReservationBusinessId for application/json ContentType.
type PostReservationBusinessIdJSONRequestBody PostReservationBusinessIdJSONBody

// PatchReservationReservationIdStatusRequestBody defines body for PatchReservationReservationIdStatus for application/json ContentType.
type PatchReservationReservationIdStatusJSONRequestBody PatchReservationReservationIdStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /reservation/{businessId})
	GetReservationBusinessId(ctx echo.Context, businessId string) error

	// (POST /reservation/{businessId})
	PostReservationBusinessId(ctx echo.Context, businessId string) error

	// (GET /reservation/{businessId}/{reservationId})
	GetReservationBusinessIdReservationId(ctx echo.Context, businessId string, reservationId string) error

	// (PATCH /reservation/{reservationId}/status)
	PatchReservationReservationIdStatus(ctx echo.Context, reservationId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReservationBusinessId(ctx, businessId)
	return err
}

// PostReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PostReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostReservationBusinessId(ctx, businessId)
	return err
}

// GetReservationBusinessIdReservationId converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservationBusinessIdReservationId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameter("simple", false, "reservationId", ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReservationBusinessIdReservationId(ctx, businessId, reservationId)
	return err
}

// PatchReservationReservationIdStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PatchReservationReservationIdStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameter("simple", false, "reservationId", ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchReservationReservationIdStatus(ctx, reservationId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/reservation/:businessId", wrapper.GetReservationBusinessId)
	router.POST(baseURL+"/reservation/:businessId", wrapper.PostReservationBusinessId)
	router.GET(baseURL+"/reservation/:businessId/:reservationId", wrapper.GetReservationBusinessIdReservationId)
	router.PATCH(baseURL+"/reservation/:reservationId/status", wrapper.PatchReservationReservationIdStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWwW7jOAz9FUG7R6NOu3tZH7szKAr0UKSY06AHxaZjFbakUnQ6QZB/H0hKGjuSgwRF",
	"Zw5zKBpLFPnI90hpw0vdGa1AkeXFhtuygU74n/8jCII5WMCVIKnVHF57sOT2DGoDSBK8JajK/aO1AV5w",
	"SyjVkm8zrkQHyQ1LAimxs832K3rxAiU52zugEQZrtLIQg8CDkfv8G6HmBf8rP+SX75LLB/7SMR+kpY8k",
	"fkl+UawzEvTfkqCzF6X6Hl0ginUazmMrSuhAJbJtQC6bYVpSESwBfcYg6HxUTyAohpPxN1lRkwqQQjof",
	"E34eM/JCpZphOU6ldKjbhfz7WkT461ZrTJc6okH13SJsTaaBmt4LFZ2yRpQwQSsJ6m3SZVhIbPQWMLlx",
	"zO4BwY/k6jqxmqrgN1MJgicPdbJVo0xOaMstSVVrZ12BLVGaUDz+VVVGS0Ws1sgccy2UxETVScU6ocTS",
	"S4CZVlCtseMZJ0mt8z1Ua8ZXgDZ4vL6auRy0ASWM5AX/52p2dcMzbgQ1Hm8+aPx8s+itVGDtfbV1m0ug",
	"GKUbKUywvSkbTQ4fC/3HfcWLo/l6++7eQ0DRAQFaXnw/DnL/hemaUQNsf4a7qvHCI+d7MfLF0CPCay8R",
	"Kl4Q9pDtrptUpzwHY7B0qyuvhFIr2jWiMKaVZajIiw2yPrg61aYTk91TPgbnF8Is9jTczGafh2I38z2M",
	"cZnnQChhBRVrHau6HrHJbF+WYG3dt+06HDfaJiQRLnMmmIK3oYdIDo/a/kl6mHzknKWI67jQA1csOK+c",
	"r2023cf5ZrBzqq/vwLX1wJgt1kxWZ7f0fBjmN/OZTcdzf2OJJsLiUS4XKumTGnvisZroa8flkMnjRo4E",
	"M9ZIfrjPjKCyicUSbkVfzKEmwzlWS2hj4Tw6V+MEDjHDBRvL5kPkTGlgfF3+omGQekhsd4NgJJh/Y+jh",
	"FOu9i9Dy/lmMq32demx5wRsiU+R5q0vRNtpSsTEaaZsLI/PVNT+WyYOzY8GNezcIlGLRBhzuYABSi74l",
	"XvD/ZrOZC/28/RkAAP//p3hv/dgNAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
