// Package reservation_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package reservation_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// CreateReservationRequest defines model for CreateReservationRequest.
type CreateReservationRequest struct {
	End   *string `json:"end,omitempty"`
	Name  *string `json:"name,omitempty"`
	Start *string `json:"start,omitempty"`
}

// CreateReservationResponse defines model for CreateReservationResponse.
type CreateReservationResponse struct {
	Reservation *Reservation `json:"reservation,omitempty"`
}

// GetReservationResponse defines model for GetReservationResponse.
type GetReservationResponse struct {
	Reservation *Reservation `json:"reservation,omitempty"`
}

// ListReservationResponse defines model for ListReservationResponse.
type ListReservationResponse struct {
	Reservations *[]Reservation `json:"reservations,omitempty"`
}

// Placement defines model for Placement.
type Placement struct {
	Height *int    `json:"height,omitempty"`
	Seats  *[]Seat `json:"seats,omitempty"`
	Width  *int    `json:"width,omitempty"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	End       *string    `json:"end,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Placement *Placement `json:"placement,omitempty"`
	Start     *string    `json:"start,omitempty"`
}

// Seat defines model for Seat.
type Seat struct {
	Floor    *int     `json:"floor,omitempty"`
	Height   *float32 `json:"height,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Rotation *float32 `json:"rotation,omitempty"`
	Space    *int     `json:"space,omitempty"`
	Status   *string  `json:"status,omitempty"`
	Type     *string  `json:"type,omitempty"`
	User     *string  `json:"user,omitempty"`
	Username *string  `json:"username,omitempty"`
	Width    *float32 `json:"width,omitempty"`
	X        *float32 `json:"x,omitempty"`
	Y        *float32 `json:"y,omitempty"`
}

// UpdateStatusRequest defines model for UpdateStatusRequest.
type UpdateStatusRequest struct {
	Status *int `json:"status,omitempty"`
}

// GetReservationBusinessIdParams defines parameters for GetReservationBusinessId.
type GetReservationBusinessIdParams struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

// PostReservationBusinessIdJSONBody defines parameters for PostReservationBusinessId.
type PostReservationBusinessIdJSONBody CreateReservationRequest

// PatchReservationReservationIdStatusJSONBody defines parameters for PatchReservationReservationIdStatus.
type PatchReservationReservationIdStatusJSONBody UpdateStatusRequest

// PostReservationBusinessIdRequestBody defines body for PostReservationBusinessId for application/json ContentType.
type PostReservationBusinessIdJSONRequestBody PostReservationBusinessIdJSONBody

// PatchReservationReservationIdStatusRequestBody defines body for PatchReservationReservationIdStatus for application/json ContentType.
type PatchReservationReservationIdStatusJSONRequestBody PatchReservationReservationIdStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /reservation/{businessId})
	GetReservationBusinessId(ctx echo.Context, businessId string, params GetReservationBusinessIdParams) error

	// (POST /reservation/{businessId})
	PostReservationBusinessId(ctx echo.Context, businessId string) error

	// (GET /reservation/{businessId}/{reservationId})
	GetReservationBusinessIdReservationId(ctx echo.Context, businessId string, reservationId string) error

	// (PATCH /reservation/{reservationId}/status)
	PatchReservationReservationIdStatus(ctx echo.Context, reservationId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReservationBusinessIdParams
	// ------------- Required query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, true, "start", ctx.QueryParams(), &params.Start)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start: %s", err))
	}

	// ------------- Required query parameter "end" -------------

	err = runtime.BindQueryParameter("form", true, true, "end", ctx.QueryParams(), &params.End)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReservationBusinessId(ctx, businessId, params)
	return err
}

// PostReservationBusinessId converts echo context to params.
func (w *ServerInterfaceWrapper) PostReservationBusinessId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostReservationBusinessId(ctx, businessId)
	return err
}

// GetReservationBusinessIdReservationId converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservationBusinessIdReservationId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "businessId" -------------
	var businessId string

	err = runtime.BindStyledParameter("simple", false, "businessId", ctx.Param("businessId"), &businessId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter businessId: %s", err))
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameter("simple", false, "reservationId", ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReservationBusinessIdReservationId(ctx, businessId, reservationId)
	return err
}

// PatchReservationReservationIdStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PatchReservationReservationIdStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameter("simple", false, "reservationId", ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchReservationReservationIdStatus(ctx, reservationId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/reservation/:businessId", wrapper.GetReservationBusinessId)
	router.POST(baseURL+"/reservation/:businessId", wrapper.PostReservationBusinessId)
	router.GET(baseURL+"/reservation/:businessId/:reservationId", wrapper.GetReservationBusinessIdReservationId)
	router.PATCH(baseURL+"/reservation/:reservationId/status", wrapper.PatchReservationReservationIdStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWTW/bOBD9KwR3j0LkZPeyOmZbBAFyCBz0VORASyOLgUQyw5FTw9B/L0jakWRRRoym",
	"aQ6BI37MezPz+Mgdz3VjtAJFlmc7bvMKGuH//R9BECzBAm4ESa2W8NyCJTdnUBtAkuBXgircD20N8Ixb",
	"QqnWvEu4Eg1EJywJpMhMlxxG9OoJcnJrIzSs0crClAf2i9zn3wglz/hfaZ9ius8vHcSLw94AfTjmnbRn",
	"g/pvSdDYs+Bf0QWi2Mbp3NcihwZUpOMVyHU17KBUBGtA31wQ9HZWDyBoSifhL7KgKgYQY7ocN+Ft6pRn",
	"itYMy3Eqpb5uZ0rd12LCv6y1xnipJ21QbbMKU7NpoKbXQk12WSNymGkrCWptNGQYiEy0FnB2Ypbhcet7",
	"ej+io9vIaKy830whCB58HrNeNknzhPDckFSldqsLsDlKEyrLv6rCaKmIlRqZa2sNOTFRNFKxRiix9vpg",
	"phZUamx4wklS7WIPpZzwDaANES8vFi4HbUAJI3nG/7lYXFzxhBtBleebDlwh3a1aKxVYe1t0bnINNGXp",
	"/IYJdljKRrbisdB/3BY8OzLE69fwngKKBgjQ8uz7McjtF6ZLRhWwwx7uqsYzz5wflMpXw4gIz61EKHhG",
	"2EKyv5aix2gXgj23gNs+Wjh27xDIucc5YR7d4uDbvitXi4X7ybWivXUIY2qZhzY92XAQ+3injGXufvBC",
	"HFd9CYQSNlCw2jVZl6PmMtvmOVhbtnW9DduNthGFhMuXCabgZRhhoo57bT+lPB7DYrB0rYvtu3Vi9m3k",
	"azmm100Ucfk7ecxr4gZo2MOJCLpk3kPS3WDmlKc4EDGCWW2ZLN5sJ8shzJ/3ljk89zc+DxFYPMrlc7jI",
	"zMv2PQQz1kja36VGUF5NxRJuZF/M5RDH72OlhHoqnHsXapxAjxku96lsfqk5cxoYX9Uf5DyxR0y3d52R",
	"YP6dUg+7WOtDFH6bf6/j5lCnFmue8YrIZGla61zUlbaU7YxG6lJhZLq55McyuXPrWAjj3iwCpVjVgYfb",
	"GIiUoq2JZ/y/xWLhoB+7nwEAAP//f3QoBnwOAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
