openapi: "3.0.2"
info:
  title: Reservation
  description: Endpoint for Seatlect admin management platform
  version: "1.0"
servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        default: "9000"
paths:
  /reservation/{businessId}:
    get:
      description: List a business reservations
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
          description: ID of the Business
        - in: query
          name: start
          required: true
          schema:
            type: string
        - in: query
          name: end
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retrieved list of reservations successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListReservationResponse"
    post:
      description: Create a new reservation
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
          description: ID of the Business
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReservationRequest"
      responses:
        "201":
          description: Get reservation successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateReservationResponse"
  /reservation/{businessId}/{reservationId}:
    get:
      description: Get a reservation by id
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
          description: ID of the Business
        - in: path
          name: reservationId
          required: true
          schema:
            type: string
          description: ID of the the reservation
      responses:
        "200":
          description: Get reservation successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetReservationResponse"
  /reservation/{reservationId}/status:
    patch:
      description: Update the Reservation status field
      parameters:
        - in: path
          name: reservationId
          required: true
          schema:
            type: string
            description: ID of the Reservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateStatusRequest"
      responses:
        "204":
          description: "Status updated"
components:
  schemas:
    Seat:
      type: object
      properties:
        name:
          type: string
        floor:
          type: integer
        type:
          type: string
        space:
          type: integer
        user:
          type: string
        username:
          type: string
        status:
          type: string
        x:
          type: number
        "y":
          type: number
        width:
          type: number
        height:
          type: number
        rotation:
          type: number
    Placement:
      type: object
      properties:
        width:
          type: integer
        height:
          type: integer
        seats:
          type: array
          items:
            $ref: "#/components/schemas/Seat"
    Reservation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        start:
          type: string
        end:
          type: string
        placement:
          type: object
          $ref: "#/components/schemas/Placement"
    CreateReservationRequest:
      type: object
      properties:
        name:
          type: string
        start:
          type: string
        end:
          type: string
    CreateReservationResponse:
      type: object
      properties:
        reservation:
          type: object
          $ref: "#/components/schemas/Reservation"
    ListReservationRequest:
      type: object
      properties:
        start:
          type: string
        end:
          type: string
    ListReservationResponse:
      type: object
      properties:
        reservations:
          type: array
          items:
            $ref: "#/components/schemas/Reservation"
    GetReservationResponse:
      type: object
      properties:
        reservation:
          $ref: "#/components/schemas/Reservation"
    UpdateStatusRequest:
      type: object
      properties:
        status:
          type: integer
