openapi: "3.0.2"
info:
  title: User
  description: Endpoint for users of the web business management platform
  version: "1.0.0"
servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        default: "9000"
paths:
  /user/register:
    post:
      description: Register the user with the given information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: Business have been created
  /user/login:
    post:
      description: Login user with given username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Authentication was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "404":
          description: Authentication failed with given credentials
        "500":
          description: Unknown error occurred
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        businessName:
          type: string
        type:
          type: string
        description:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
        address:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - "username"
        - "password"
    LoginResponse:
      type: object
      properties:
        _id:
          type: string
