// Package user_api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package user_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Id *string `json:"_id,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Address      *string `json:"address,omitempty"`
	BusinessName *string `json:"businessName,omitempty"`
	Description  *string `json:"description,omitempty"`
	Email        *string `json:"email,omitempty"`
	Location     *struct {
		Latitude  *float32 `json:"latitude,omitempty"`
		Longitude *float32 `json:"longitude,omitempty"`
	} `json:"location,omitempty"`
	Password *string `json:"password,omitempty"`
	Policy   *struct {
		MinAge *int `json:"minAge,omitempty"`
	} `json:"policy,omitempty"`
	Type     *string `json:"type,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostUserLoginJSONBody defines parameters for PostUserLogin.
type PostUserLoginJSONBody LoginRequest

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody RegisterRequest

// PostUserLoginRequestBody defines body for PostUserLogin for application/json ContentType.
type PostUserLoginJSONRequestBody PostUserLoginJSONBody

// PostUserRegisterRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /user/login)
	PostUserLogin(ctx echo.Context) error

	// (POST /user/register)
	PostUserRegister(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostUserLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserLogin(ctx)
	return err
}

// PostUserRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserRegister(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/user/login", wrapper.PostUserLogin)
	router.POST(baseURL+"/user/register", wrapper.PostUserRegister)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RVXWvcOhD9K2LufTRrJ/f2oX5LoA+FUkogTyEUrT22lcqSMjPeJSz734skbzeb9ZYW",
	"2jdLI50zH+fIO2j8GLxDJwz1DrgZcNTp85PvjbvD5wlZ4jqQD0hiMEWDZt56auO3vASEGljIuB72BUyM",
	"5PSIC8F9AYTPkyFsoX44niyOiI/F4ZJfP2EjEXFOhoN3jOfZfDXtMtcZ0B32hgXpYmG6bQmZF+taT2wc",
	"Mn9erq2AFrkhE8R4txjHURu7GLG+0YdrpwlZLUam9jWhm8Y1Ur7m+kvRpfJ/OrbgrWlezjMYjbvpXzMY",
	"J9hfosgbv62KNzhxy7jOx8MnXYUPrg3eOFGdJxUxWflOyYBqi2t1GJEatdM9juhEBaul8zRCAWLERpp7",
	"RoICNkicUa9W1aqKWfqATgcDNfy3qlbXSZgypD6Uka20UYqpST7r5zS9pNSUl9oaGVRvNpjXsXalXat+",
	"DCGxUZr7xxZq+OJZYmYJA7JTkOXWt2kqjXeCLnHqEKzJiimfOMsmezd+/UvYQQ3/lEdzl7OzyxNb70/9",
	"KDRh2sg+S0VfV9Wf5p5dnMhPm3czyYBOZnS11ax4ahpk7iYbp/N/dXXe8je3Om0stq+73xC28YC2HEHe",
	"5ZJOQe7dN+e3TiGRJ+WbZqLYk33KMk+e5rfj8vAPr0uS41EDcZUziZKmMTv90vQPIH9JAG9fwF/SwELX",
	"bw9OG/QG1Rpzn7XMTdsXwEjRYFA/7GAiCzUMIqEuy/jY2cGz1LvgSfalDqbcXEFx5qVGW5Vhols1Gb22",
	"8w/I0zyATk9WoIb3VVVF6sf99wAAAP//8RCy6NYGAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
